### ISSUE TITLE
Plural of nouns and inflections of verbs

### ISSUE THREAD

**Issue by fuglede** [t-veor/ordill#1]
A few days ago, the word to find was "bökur"; many of the other popular versions avoid using plural forms of nouns and inflections of verbs, thus drastically reducing the set of possible solutions. Looks like that's not the case here?

**Comment by t-veor** [comment]
Hello, thanks for playing my game! This is completely intentional (in fact the instructions page deliberately uses "töflu" as one of the examples to demonstrate this), although it is the case that nominative singular forms of nouns/adjectives and infinitive forms of verbs are slightly more likely to show up.

Like Wordle, Orðill employs two word lists -- one is the more restricted pool of words from which Orðill will pick a solution, and another is a larger list containing all the possible 5-letter words that are accepted as guesses. You can see this restricted pool of words here: https://github.com/t-veor/ordill/blob/main/src/words/common.wordlist.txt

I decided to add declined versions of words because:
* There would be a big lack of variety in the word list. Almost all infinitive verbs in Icelandic end with A, all weak masculine nouns in nominative end with I, all weak feminine nouns in nominative end with A. The word list would be extremely biased towards these letters (the first version of the game had over 50% of the words ending with A!) if other forms of words were not included.
* Undeclined words are actually fairly uncommon in Icelandic. Verbs in infinitive pretty much only exist in the "ég er að gera..." construction, and pretty much every transitive verb takes their object in accusative or dative case so that the nominative case is restricted to subjects. Even then, impersonal constructions that take the subject in a different case such as "mér líður..." and "mig langar..." are extremely common.
* Ostensibly I made this to help learn me learn Icelandic, and part of that is getting used to declining words and common declension patterns.

This definitely makes the actual game a lot harder, but that's why there's an infinite guess mode :)
